import { Listing } from './types';

export const SEED_LISTINGS: Listing[] = [
    // --- Stays (5) ---
    {
        id: 'stay-1',
        title: 'Blue Mountain Peak Cabin',
        category: 'stay',
        parish: 'St. Thomas',
        location: 'Blue Mountain Peak, St. Thomas',
        description: 'A rustic cabin perched near the summit of the Blue Mountains. Perfect for hikers and nature lovers seeking tranquility and breathtaking sunrise views.',
        images: ['https://images.unsplash.com/photo-1449156493391-d2cfa28e468b?q=80&w=2072&auto=format&fit=crop'],
        priceFrom: 120,
        rating: 4.8,
        reviewsCount: 124,
        amenities: ['Mountain View', 'Hiking Trails', 'Fireplace', 'Kitchenette'],
        rules: ['No loud music', 'Check-in 2 PM', 'Pack out what you pack in'],
        coordinates: { lat: 18.046, lng: -76.579 }
    },
    {
        id: 'stay-2',
        title: 'Negril Beachfront Villa',
        category: 'stay',
        parish: 'Westmoreland',
        location: 'Seven Mile Beach, Negril',
        description: 'Luxury villa right on the famous Seven Mile Beach. Enjoy private beach access, a personal chef, and stunning sunsets every evening.',
        images: ['https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=2070&auto=format&fit=crop'],
        priceFrom: 450,
        rating: 4.9,
        reviewsCount: 89,
        amenities: ['Beach Access', 'Pool', 'Wifi', 'Air Conditioning', 'Chef'],
        rules: ['No smoking indoors', 'No pets'],
        coordinates: { lat: 18.278, lng: -78.344 }
    },
    {
        id: 'stay-3',
        title: 'Port Antonio Eco-Lodge',
        category: 'stay',
        parish: 'Portland',
        location: 'San San, Portland',
        description: 'Sustainable eco-lodge nestled in the lush rainforest of Portland. Close to the Blue Lagoon and Frenchman\'s Cove.',
        images: ['https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?q=80&w=2070&auto=format&fit=crop'],
        priceFrom: 180,
        rating: 4.7,
        reviewsCount: 56,
        amenities: ['Rainforest View', 'Organic Breakfast', 'Yoga Deck', 'Wifi'],
        rules: ['Quiet hours 10 PM', 'Eco-friendly products only'],
        coordinates: { lat: 18.173, lng: -76.438 }
    },
    {
        id: 'stay-4',
        title: 'Treasure Beach Cottage',
        category: 'stay',
        parish: 'St. Elizabeth',
        location: 'Treasure Beach, St. Elizabeth',
        description: 'Charming seaside cottage in the laid-back community of Treasure Beach. Experience authentic Jamaican hospitality and community tourism.',
        images: ['https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?q=80&w=2070&auto=format&fit=crop'],
        priceFrom: 90,
        rating: 4.6,
        reviewsCount: 203,
        amenities: ['Ocean View', 'Hammocks', 'Full Kitchen', 'Bicycles'],
        rules: ['Respect the neighbors'],
        coordinates: { lat: 17.886, lng: -77.771 }
    },
    {
        id: 'stay-5',
        title: 'Ocho Rios Garden Apartment',
        category: 'stay',
        parish: 'St. Ann',
        location: 'Main Street, Ocho Rios',
        description: 'Modern apartment in the heart of Ocho Rios. Walking distance to shops, restaurants, and the beach.',
        images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=2070&auto=format&fit=crop'],
        priceFrom: 110,
        rating: 4.5,
        reviewsCount: 75,
        amenities: ['Pool', 'Gym', 'Security', 'Wifi'],
        rules: ['No parties'],
        coordinates: { lat: 18.406, lng: -77.103 }
    },

    // --- Tours (4) ---
    {
        id: 'tour-1',
        title: 'Dunn\'s River Falls Adventure',
        category: 'tour',
        parish: 'St. Ann',
        location: 'Ocho Rios, St. Ann',
        description: 'Climb the world-famous Dunn\'s River Falls. A refreshing and exhilarating adventure for the whole family.',
        images: ['https://images.unsplash.com/photo-1596895311029-43c3d550f24f?q=80&w=2026&auto=format&fit=crop'],
        priceFrom: 50,
        rating: 4.7,
        reviewsCount: 3042,
        amenities: ['Guide provided', 'Lockers available'],
        included: ['Entrance fee', 'Guide', 'Water shoes rental'],
        coordinates: { lat: 18.415, lng: -77.135 }
    },
    {
        id: 'tour-2',
        title: 'Rafting on the Martha Brae',
        category: 'tour',
        parish: 'Trelawny',
        location: 'Martha Brae, Trelawny',
        description: 'Relax on a bamboo raft as you glide down the Martha Brae River. Learn about the legend of Martha Brae from your captain.',
        images: ['https://images.unsplash.com/photo-1626946660124-73895e691238?q=80&w=1974&auto=format&fit=crop'],
        priceFrom: 75,
        rating: 4.6,
        reviewsCount: 890,
        amenities: ['Transportation', 'Bar'],
        included: ['Raft ride', 'Welcome drink'],
        coordinates: { lat: 18.476, lng: -77.656 }
    },
    {
        id: 'tour-3',
        title: 'Bob Marley Museum Tour',
        category: 'tour',
        parish: 'St. Andrew',
        location: '56 Hope Road, Kingston',
        description: 'Visit the former home and studio of reggae legend Bob Marley. immerse yourself in the life and music of the icon.',
        images: ['https://images.unsplash.com/photo-1550600366-03bf47796dcd?q=80&w=2070&auto=format&fit=crop'], // Placeholder music vibe
        priceFrom: 25,
        rating: 4.8,
        reviewsCount: 1500,
        amenities: ['Gift Shop', 'Cafe'],
        included: ['Guided tour', 'Film screening'],
        coordinates: { lat: 18.019, lng: -76.782 }
    },
    {
        id: 'tour-4',
        title: 'Blue Lagoon & Monkey Island',
        category: 'tour',
        parish: 'Portland',
        location: 'Port Antonio, Portland',
        description: 'Boat tour of the mystical Blue Lagoon and a stop at Monkey Island for swimming and snorkeling.',
        images: ['https://images.unsplash.com/photo-1587595431973-160fa0d94aaa?q=80&w=2076&auto=format&fit=crop'],
        priceFrom: 60,
        rating: 4.5,
        reviewsCount: 420,
        amenities: ['Boat', 'Life jackets'],
        included: ['Boat ride', 'Snorkel gear'],
        coordinates: { lat: 18.171, lng: -76.417 }
    },

    // --- Restaurants (3) ---
    {
        id: 'rest-1',
        title: 'Scotchies Jerk Centre',
        category: 'restaurant',
        parish: 'St. James',
        location: 'Montego Bay, St. James',
        description: 'Authentic Jamaican jerk chicken and pork cooked over pimento wood. A casual, open-air dining experience.',
        images: ['https://images.unsplash.com/photo-1594957648356-aa49553755c3?q=80&w=2072&auto=format&fit=crop'], // Placeholder food
        priceFrom: 15,
        rating: 4.7,
        reviewsCount: 2200,
        amenities: ['Outdoor Seating', 'Bar', 'Takeout'],
        included: ['Service charge'],
        coordinates: { lat: 18.498, lng: -77.892 }
    },
    {
        id: 'rest-2',
        title: 'Rick\'s Cafe',
        category: 'restaurant',
        parish: 'Westmoreland',
        location: 'West End, Negril',
        description: 'World-famous bar and restaurant known for its cliff diving and spectacular sunset views. Live music daily.',
        images: ['https://images.unsplash.com/photo-1544148103-0773bf10d330?q=80&w=2070&auto=format&fit=crop'],
        priceFrom: 30,
        rating: 4.4,
        reviewsCount: 5000,
        amenities: ['Live Music', 'Pool', 'Cliff Diving'],
        included: ['Sunset view'],
        coordinates: { lat: 18.250, lng: -78.368 }
    },
    {
        id: 'rest-3',
        title: 'Devon House Bakery',
        category: 'restaurant',
        parish: 'St. Andrew',
        location: 'Hope Road, Kingston',
        description: 'Enjoy world-famous patties and ice cream on the grounds of the historic Devon House mansion.',
        images: ['https://images.unsplash.com/photo-1555244162-803834f70033?q=80&w=2070&auto=format&fit=crop'],
        priceFrom: 10,
        rating: 4.8,
        reviewsCount: 1800,
        amenities: ['Garden Seating', 'Parking'],
        included: ['Historic ambience'],
        coordinates: { lat: 18.024, lng: -76.790 }
    }
];
